stages:
  - docs

pages:
  image: griefed/baseimage-ubuntu-jdk-8:1.0.5
  stage: docs
  services:
    - name: griefed/gitlab-ci-cd:1.0.2
      alias: docker
  variables:
    project_name: $CI_PROJECT_NAME
    SEMANTIC_RELEASE_PACKAGE: $CI_PROJECT_NAME
  before_script:
    - which java
    - chmod +x gradlew
    - ./gradlew clean
  script:
    - ./gradlew javaDoc
    - cp -Rf build/docs/javadoc public
    - LC_COLLATE=C ls -ahl --group-directories-first --color=auto
      public
  artifacts:
    paths:
      - public
    expire_in: 1 week
