stages:
  - docs
  - gradle

Gradle Test:
  image: griefed/baseimage-ubuntu-jdk-8:2.0.7
  stage: gradle
  services:
    - name: griefed/gitlab-ci-cd:2.0.4
      alias: docker
  variables:
    project_name: $CI_PROJECT_NAME
    SEMANTIC_RELEASE_PACKAGE: $CI_PROJECT_NAME
  before_script:
    - echo "**** Running in $CI_JOB_ID ****"
    - echo "**** Java location ****"
    - which java
    - echo "**** Java version ****"
    - java -version
    - echo "**** Allowing execution of gradlew ****"
    - chmod +x gradlew
    - echo "**** Ensure clean environment ****"
    - ./gradlew clean
  script:
    - echo "**** Building hastebin-java ****"
    - ./gradlew build --info
  except:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TITLE =~ /^RELEASE:.+$/


pages:
  image: griefed/baseimage-ubuntu-jdk-8:2.0.7
  stage: docs
  services:
    - name: griefed/gitlab-ci-cd:2.0.4
      alias: docker
  variables:
    project_name: $CI_PROJECT_NAME
    SEMANTIC_RELEASE_PACKAGE: $CI_PROJECT_NAME
  before_script:
    - which java
    - chmod +x gradlew
    - ./gradlew clean
  script:
    - ./gradlew javaDoc
    - cp -Rf build/docs/javadoc public
    - LC_COLLATE=C ls -ahl --group-directories-first --color=auto
      public
  artifacts:
    paths:
      - public
    expire_in: 1 week
